//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWCF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes_Result4", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class Clientes_Result4 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int client_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string password_clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int client_id {
            get {
                return this.client_idField;
            }
            set {
                if ((this.client_idField.Equals(value) != true)) {
                    this.client_idField = value;
                    this.RaisePropertyChanged("client_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password_client {
            get {
                return this.password_clientField;
            }
            set {
                if ((object.ReferenceEquals(this.password_clientField, value) != true)) {
                    this.password_clientField = value;
                    this.RaisePropertyChanged("password_client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteGuardar_Result3", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class ClienteGuardar_Result3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos_Result2", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class Productos_Result2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_brandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_brand {
            get {
                return this.name_brandField;
            }
            set {
                if ((object.ReferenceEquals(this.name_brandField, value) != true)) {
                    this.name_brandField = value;
                    this.RaisePropertyChanged("name_brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_category {
            get {
                return this.name_categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.name_categoryField, value) != true)) {
                    this.name_categoryField = value;
                    this.RaisePropertyChanged("name_category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario_Result1", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class Usuario_Result1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string password_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password_user {
            get {
                return this.password_userField;
            }
            set {
                if ((object.ReferenceEquals(this.password_userField, value) != true)) {
                    this.password_userField = value;
                    this.RaisePropertyChanged("password_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                if ((object.ReferenceEquals(this.rolField, value) != true)) {
                    this.rolField = value;
                    this.RaisePropertyChanged("rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioGuardar_Result3", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class UsuarioGuardar_Result3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductGuardar_Result1", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class ProductGuardar_Result1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientesLista", ReplyAction="http://tempuri.org/IService1/clientesListaResponse")]
        WebWCF.ServiceReference1.Clientes_Result4[] clientesLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientesLista", ReplyAction="http://tempuri.org/IService1/clientesListaResponse")]
        System.Threading.Tasks.Task<WebWCF.ServiceReference1.Clientes_Result4[]> clientesListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientesGuardar", ReplyAction="http://tempuri.org/IService1/clientesGuardarResponse")]
        WebWCF.ServiceReference1.ClienteGuardar_Result3 clientesGuardar(int Id, string nombre, string telefono, string email, string password, string validate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientesGuardar", ReplyAction="http://tempuri.org/IService1/clientesGuardarResponse")]
        System.Threading.Tasks.Task<WebWCF.ServiceReference1.ClienteGuardar_Result3> clientesGuardarAsync(int Id, string nombre, string telefono, string email, string password, string validate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/productosLista", ReplyAction="http://tempuri.org/IService1/productosListaResponse")]
        WebWCF.ServiceReference1.Productos_Result2[] productosLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/productosLista", ReplyAction="http://tempuri.org/IService1/productosListaResponse")]
        System.Threading.Tasks.Task<WebWCF.ServiceReference1.Productos_Result2[]> productosListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usuariosLista1", ReplyAction="http://tempuri.org/IService1/usuariosLista1Response")]
        WebWCF.ServiceReference1.Usuario_Result1[] usuariosLista1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usuariosLista1", ReplyAction="http://tempuri.org/IService1/usuariosLista1Response")]
        System.Threading.Tasks.Task<WebWCF.ServiceReference1.Usuario_Result1[]> usuariosLista1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usuarioGuardar", ReplyAction="http://tempuri.org/IService1/usuarioGuardarResponse")]
        WebWCF.ServiceReference1.UsuarioGuardar_Result3 usuarioGuardar(int Id, string nombre, string telefono, string email, string username, string password, int rol, string validate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usuarioGuardar", ReplyAction="http://tempuri.org/IService1/usuarioGuardarResponse")]
        System.Threading.Tasks.Task<WebWCF.ServiceReference1.UsuarioGuardar_Result3> usuarioGuardarAsync(int Id, string nombre, string telefono, string email, string username, string password, int rol, string validate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/productGuardar", ReplyAction="http://tempuri.org/IService1/productGuardarResponse")]
        WebWCF.ServiceReference1.ProductGuardar_Result1 productGuardar(int Id, string nombre, int brand, string description, int category, string validate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/productGuardar", ReplyAction="http://tempuri.org/IService1/productGuardarResponse")]
        System.Threading.Tasks.Task<WebWCF.ServiceReference1.ProductGuardar_Result1> productGuardarAsync(int Id, string nombre, int brand, string description, int category, string validate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usuarioDatos", ReplyAction="http://tempuri.org/IService1/usuarioDatosResponse")]
        WebWCF.ServiceReference1.Usuario_Result1 usuarioDatos(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usuarioDatos", ReplyAction="http://tempuri.org/IService1/usuarioDatosResponse")]
        System.Threading.Tasks.Task<WebWCF.ServiceReference1.Usuario_Result1> usuarioDatosAsync(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/productDatos", ReplyAction="http://tempuri.org/IService1/productDatosResponse")]
        WebWCF.ServiceReference1.Productos_Result2 productDatos(int IdProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/productDatos", ReplyAction="http://tempuri.org/IService1/productDatosResponse")]
        System.Threading.Tasks.Task<WebWCF.ServiceReference1.Productos_Result2> productDatosAsync(int IdProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientesDatos", ReplyAction="http://tempuri.org/IService1/clientesDatosResponse")]
        WebWCF.ServiceReference1.Clientes_Result4 clientesDatos(int IdClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientesDatos", ReplyAction="http://tempuri.org/IService1/clientesDatosResponse")]
        System.Threading.Tasks.Task<WebWCF.ServiceReference1.Clientes_Result4> clientesDatosAsync(int IdClient);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebWCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebWCF.ServiceReference1.IService1>, WebWCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WebWCF.ServiceReference1.Clientes_Result4[] clientesLista() {
            return base.Channel.clientesLista();
        }
        
        public System.Threading.Tasks.Task<WebWCF.ServiceReference1.Clientes_Result4[]> clientesListaAsync() {
            return base.Channel.clientesListaAsync();
        }
        
        public WebWCF.ServiceReference1.ClienteGuardar_Result3 clientesGuardar(int Id, string nombre, string telefono, string email, string password, string validate) {
            return base.Channel.clientesGuardar(Id, nombre, telefono, email, password, validate);
        }
        
        public System.Threading.Tasks.Task<WebWCF.ServiceReference1.ClienteGuardar_Result3> clientesGuardarAsync(int Id, string nombre, string telefono, string email, string password, string validate) {
            return base.Channel.clientesGuardarAsync(Id, nombre, telefono, email, password, validate);
        }
        
        public WebWCF.ServiceReference1.Productos_Result2[] productosLista() {
            return base.Channel.productosLista();
        }
        
        public System.Threading.Tasks.Task<WebWCF.ServiceReference1.Productos_Result2[]> productosListaAsync() {
            return base.Channel.productosListaAsync();
        }
        
        public WebWCF.ServiceReference1.Usuario_Result1[] usuariosLista1() {
            return base.Channel.usuariosLista1();
        }
        
        public System.Threading.Tasks.Task<WebWCF.ServiceReference1.Usuario_Result1[]> usuariosLista1Async() {
            return base.Channel.usuariosLista1Async();
        }
        
        public WebWCF.ServiceReference1.UsuarioGuardar_Result3 usuarioGuardar(int Id, string nombre, string telefono, string email, string username, string password, int rol, string validate) {
            return base.Channel.usuarioGuardar(Id, nombre, telefono, email, username, password, rol, validate);
        }
        
        public System.Threading.Tasks.Task<WebWCF.ServiceReference1.UsuarioGuardar_Result3> usuarioGuardarAsync(int Id, string nombre, string telefono, string email, string username, string password, int rol, string validate) {
            return base.Channel.usuarioGuardarAsync(Id, nombre, telefono, email, username, password, rol, validate);
        }
        
        public WebWCF.ServiceReference1.ProductGuardar_Result1 productGuardar(int Id, string nombre, int brand, string description, int category, string validate) {
            return base.Channel.productGuardar(Id, nombre, brand, description, category, validate);
        }
        
        public System.Threading.Tasks.Task<WebWCF.ServiceReference1.ProductGuardar_Result1> productGuardarAsync(int Id, string nombre, int brand, string description, int category, string validate) {
            return base.Channel.productGuardarAsync(Id, nombre, brand, description, category, validate);
        }
        
        public WebWCF.ServiceReference1.Usuario_Result1 usuarioDatos(int IdUsuario) {
            return base.Channel.usuarioDatos(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<WebWCF.ServiceReference1.Usuario_Result1> usuarioDatosAsync(int IdUsuario) {
            return base.Channel.usuarioDatosAsync(IdUsuario);
        }
        
        public WebWCF.ServiceReference1.Productos_Result2 productDatos(int IdProduct) {
            return base.Channel.productDatos(IdProduct);
        }
        
        public System.Threading.Tasks.Task<WebWCF.ServiceReference1.Productos_Result2> productDatosAsync(int IdProduct) {
            return base.Channel.productDatosAsync(IdProduct);
        }
        
        public WebWCF.ServiceReference1.Clientes_Result4 clientesDatos(int IdClient) {
            return base.Channel.clientesDatos(IdClient);
        }
        
        public System.Threading.Tasks.Task<WebWCF.ServiceReference1.Clientes_Result4> clientesDatosAsync(int IdClient) {
            return base.Channel.clientesDatosAsync(IdClient);
        }
    }
}
