//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWCF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class andinoshopEntities : DbContext
    {
        public andinoshopEntities()
            : base("name=andinoshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<type_user> type_user { get; set; }
        public virtual DbSet<brand> brand { get; set; }
        public virtual DbSet<category> category { get; set; }
    
        public virtual ObjectResult<string> Roles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Roles");
        }
    
        public virtual ObjectResult<Roles_Result> Roles_Result()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Roles_Result>("Roles_Result");
        }
    }
}
